version: "2"

services:
  db:
    image: mysql
    restart: always
    env_file:
      - my_sql_env
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my-db:
