version: "2"

services:
  app:
    build:
      dockerfile: ./app_dockerfile
      context: .
    depends_on:
      - db
  db:
    image: mysql
    restart: always
    env_file:
      - my_sql_env
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  my-db:
