version: "2"

services:
  app:
    build:
      dockerfile: ./app_dockerfile
      context: .
    environment:
      DISPLAY: LAPTOP-JKTNU2F0:0
      USER: "$whoami"
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /c/Users/$USER:/home/$USER:rw
  db:
    image: mysql
    restart: always
    env_file:
      - my_sql_env
    volumes:
      - my-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  my-db:
