FROM python

RUN apt-get update && \
    apt-get install -y build-essential

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir Scrapy beautifulsoup4

COPY ./webscraping.py .

CMD ["python","webscraping.py"]
